apiVersion: v1
clusters:
- name: RSO
  cluster:
    certificate-authority: ca-mil01-RSO.pem
    server: https://c6.mil01.containers.cloud.ibm.com:30755
contexts:
- name: RSO
  context:
    cluster: RSO
    user: ma6795@student.uni-lj.si
    namespace: default
current-context: RSO
kind: Config
users:
- name: ma6795@student.uni-lj.si
  user:
    auth-provider:
      name: oidc
      config:
        client-id: bx
        client-secret: bx
        id-token: eyJraWQiOiIyMDE3MTAzMC0wMDowMDowMCIsImFsZyI6IlJTMjU2In0.eyJpYW1faWQiOiJJQk1pZC01NTAwMDIwTVRBIiwiaXNzIjoiaHR0cHM6Ly9pYW0ubmcuYmx1ZW1peC5uZXQva3ViZXJuZXRlcyIsInN1YiI6Im1hNjc5NUBzdHVkZW50LnVuaS1sai5zaSIsImF1ZCI6ImJ4IiwiZ2l2ZW5fbmFtZSI6Ik1hcmtvIiwiZmFtaWx5X25hbWUiOiJBbWJyb8W-acSNIiwibmFtZSI6Ik1hcmtvIEFtYnJvxb5pxI0iLCJlbWFpbCI6Im1hNjc5NUBzdHVkZW50LnVuaS1sai5zaSIsImV4cCI6MTU0NjAyNjk3NSwic2NvcGUiOiJpYm0gb3BlbmlkIiwiaWF0IjoxNTQ2MDIzMzc1fQ.DYIiUWd0vTTpWHDbdqQrE351c5hJzKNZVHPnY8p0E_mUEB8LTEEzVQxdCDSzNbyMxoReI9sXw117XBQXIdhnsKz8-crvfCd3vG04EvcrwCShl8whar6arm4SoGI28GHoOqBWJHCxxSiCWciUIW7S3YrbV6iSfHpi8K9CYSoC_PaDMQSR4-eoSHmn9s1wgxpEZeb4hiuUAYlt8h3wEwdBSQz4XWlRoc-uOgCQZu063NO-HlMMxzHRLXr5BDJgEh37idkL3PFyjBydh30otxlGebFdXJhrJawQ7BQV59OuN4zFzJ0mUDjeSv771PDfu2kziYe_hnC6-tFvBPvZatqxFg
        idp-issuer-url: https://iam.ng.bluemix.net/kubernetes
        refresh-token: J1CyKAnDv101oGDYR4uxI9oUKlqHOBaOt0o6SnugB2UybPiTBvNa_-OIyULZzN47ETHHu2FLUBbvnFCvlq8ddm9SHvpjXI2BXK_tiyy8GTVlNIJUbtQaaGrjFaxhLeYKZjpsruH-QBODPe2lzUzOKvDGf4B5a5yCFGy58Qs-hUKxSXX_15_l6fhCGkiDwhV2Tdq2KBb1HZ76G6wIqnSnhHnoatitGrMqnZWxYlA4-Qy7DFSjKAd51t-W8N64cL7Zvvr3OJAxwmUsanzsaOBeOohhRhP_UgxtwEbUXzYi8wbLHRTQl4z4xuwsprj_-edwR_8Mpr6JBK5DI53MaduGbbVakhbiyYbkxD5Vi3zvMrduQwRaHiVp2tlAFiaNCTW1gnCUM9IpmkIh82m8PyfGYYPc_9WAy0R_3aseYkk5lkaBo502ANmUEcxG6hFgqwAg4AaGnpCvZ9grBDs-km241TSdsLcjPEM8ZJL6S29OlakVqPgmkSJgH8oP5diIRaAHprqi9WQcnCPIf8qdq9-DM-JQqO3bThTBMglLPpSaMQKyMYg5SBGx6-j-xB-8oLihmyMWOmuFTF4TU9Fg-TZCGqvs_GyiQVNi0Rvtfvo3LpZ-goU1nng95X2JEWGr7Wt59j6kWynuj1uKghfFjE3p6mutEUGWWUp2L7qUguzuDKD0fxkzc2r3u69xE7horLwRc0sVMdRyVhS7S0-dHfL2r0D2uzY3iDD-de7Ldm1hz7KoHAAlYQVrCwruoZOfz1uNiD1TwZWPvRZYPN9aXjMNFD4XaJSgpUUQyVGF6-6ITx6e_adVcFT4tJCoHxAjAo-RKS018jb3x7Y8e8wnm2pmMYsYInAYNoiQVYT_nJ56dWoSPN8GO5HI0M5Ups0yQFs9csJCfMze1rotqqA4Tek8f2wrWjmBGWfGf1B-cupzo4L-2Q
